ezconfig_manager.environment_config:
  path: '/admin/config/development/configuration/environment/config'
  defaults:
    _title: 'Environment config'
    _form: '\Drupal\ezconfig_manager\Form\EnvironmentConfigForm'
  requirements:
    _permission: 'import configuration'
