#Loaded by Drush\Drupal\DrupalKernel::discoverServiceProviders
services:
  ezconfig.export.commands:
    class: \Drupal\ezconfig_manager\Commands\config\EzConfigExportCommands
    arguments: ['@config.manager', '@config.storage', '@config.storage.sync']
    tags:
      -  { name: drush.command }
  ezconfig.import.commands:
    class: \Drupal\ezconfig_manager\Commands\config\EzConfigImportCommands
    arguments: ['@config.manager', '@config.storage', '@config.storage.sync', '@module_handler', '@event_dispatcher', '@lock', '@config.typed', '@module_installer', '@theme_handler', '@string_translation']
    tags:
      -  { name: drush.command }
